/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package applibrary;

/**
 *
 * @author Software-19
 */
public class FormDataFixed extends javax.swing.JFrame {

    /**
     * Creates new form FormMemberData
     */
    public FormDataFixed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_alamat2 = new javax.swing.JTextField();
        txt_nama2 = new javax.swing.JTextField();
        txt_kelas2 = new javax.swing.JTextField();
        txt_nis2 = new javax.swing.JTextField();
        txt_kompetensi2 = new javax.swing.JTextField();
        txt_jk2 = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        var_female = new javax.swing.JRadioButton();
        var_male = new javax.swing.JRadioButton();
        cmb_kelas = new javax.swing.JComboBox<>();
        cmb_kompetensi = new javax.swing.JComboBox<>();
        btn_submit1 = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 122, 37));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Data Anggota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        txt_nama.setForeground(new java.awt.Color(102, 102, 102));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txt_nis.setForeground(new java.awt.Color(102, 102, 102));
        txt_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nisActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Kelas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        btn_delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setBorderPainted(false);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        btn_back.setBackground(new java.awt.Color(153, 153, 153));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorderPainted(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kompetensi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Data Anggota");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));
        jPanel2.add(txt_alamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 210, -1));

        txt_nama2.setForeground(new java.awt.Color(102, 102, 102));
        txt_nama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 210, -1));

        txt_kelas2.setForeground(new java.awt.Color(102, 102, 102));
        txt_kelas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kelas2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_kelas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        txt_nis2.setForeground(new java.awt.Color(102, 102, 102));
        txt_nis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nis2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, -1));

        txt_kompetensi2.setForeground(new java.awt.Color(102, 102, 102));
        txt_kompetensi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kompetensi2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_kompetensi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, -1));
        jPanel2.add(txt_jk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 60, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 520, 250));
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        buttonGroup1.add(var_female);
        var_female.setText("Perempuan");
        jPanel1.add(var_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        buttonGroup1.add(var_male);
        var_male.setText("Laki-laki");
        var_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_maleActionPerformed(evt);
            }
        });
        jPanel1.add(var_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        cmb_kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kelas --", "X", "Sebelas", "12" }));
        cmb_kelas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_kelasItemStateChanged(evt);
            }
        });
        cmb_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_kelasMouseClicked(evt);
            }
        });
        cmb_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kelasActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, -1));

        cmb_kompetensi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kompetensi --", "Rekayasa Perangkat Lunak", "Desain Komunikasi Visual", "Teknik Komputer Jaringan" }));
        jPanel1.add(cmb_kompetensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 210, -1));

        btn_submit1.setBackground(new java.awt.Color(51, 153, 255));
        btn_submit1.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disk (1).png"))); // NOI18N
        btn_submit1.setText("Save");
        btn_submit1.setBorderPainted(false);
        btn_submit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        btn_edit.setBackground(new java.awt.Color(255, 102, 51));
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (1).png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setBorderPainted(false);
        btn_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nisActionPerformed

    private void clear(){
        txt_nama.setText("");
        txt_nis.setText("");
        cmb_kelas.setSelectedItem(0);
        cmb_kompetensi.setSelectedItem(0);
        txt_alamat.setText("");
        buttonGroup1.clearSelection();
        
        txt_nama2.setText("");
        txt_nis2.setText("");
        txt_kelas2.setText("");
        txt_kompetensi2.setText("");
        txt_jk2.setText("");
        txt_alamat2.setText("");
        
    }
    
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String nama;
        String nis;
        String kelas;
        String kompetensi;
        String jk;
        String alamat;
        
        nama = txt_nama.getText();
        nis = txt_nis.getText();
        kelas = cmb_kelas.getSelectedItem().toString();
        kompetensi = cmb_kompetensi.getSelectedItem().toString();
        alamat = txt_alamat.getText();
        
        if(var_male.isSelected()){
            jk = "L";
        }else{
            jk = "P";
        }
        
        txt_nama2.setText(nama);
        txt_nama2.setEditable(false);
        
        txt_nis2.setText(nis);
        txt_nis2.setEditable(false);
        
        txt_kelas2.setText(kelas);
        txt_kelas2.setEditable(false);
        
        txt_kompetensi2.setText(kompetensi);
        txt_kompetensi2.setEditable(false);
        
        txt_jk2.setText(jk);
        txt_jk2.setEditable(false);
        
        txt_alamat2.setText(alamat);
        txt_alamat2.setEditable(false);
        
        
        txt_nama.setText("");
        txt_nis.setText("");
        cmb_kelas.setSelectedItem(0);
        cmb_kompetensi.setSelectedItem(0);
        txt_alamat.setText("");
        buttonGroup1.clearSelection();
        
        txt_nama.requestFocus();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        clear();
        
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_nis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nis2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nis2ActionPerformed

    private void txt_nama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama2ActionPerformed

    private void txt_kelas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kelas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kelas2ActionPerformed

    private void txt_kompetensi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kompetensi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kompetensi2ActionPerformed

    private void var_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_maleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_var_maleActionPerformed

    private void cmb_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kelasActionPerformed

    private void cmb_kelasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kelasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kelasItemStateChanged

    private void cmb_kelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_kelasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kelasMouseClicked

    private void btn_submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_submit1ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormDataFixed().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_submit1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb_kelas;
    private javax.swing.JComboBox<String> cmb_kompetensi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_alamat2;
    private javax.swing.JTextField txt_jk2;
    private javax.swing.JTextField txt_kelas2;
    private javax.swing.JTextField txt_kompetensi2;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama2;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JTextField txt_nis2;
    private javax.swing.JRadioButton var_female;
    private javax.swing.JRadioButton var_male;
    // End of variables declaration//GEN-END:variables
}
